# Generated by Django 5.1.7 on 2025-03-31 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_comments_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='foto',
        ),
    ]
