# Generated by Django 5.1.7 on 2025-03-31 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_comments_app', '0002_remove_comentario_foto_remove_resposta_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='reposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='interactive_comments_app.resposta'),
        ),
    ]
