# Generated by Django 5.1.7 on 2025-03-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_comments_app', '0003_like_reposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(upload_to=''),
        ),
    ]
